[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "glare eternal august long hurt cricket catalog garlic unknown vehicle forum cruel"
