[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "desert replace point glare unit shift heart kid sample motor stock lizard public spirit crime attract quarter motor volume good mimic smart item prevent"
# After adding your mnemonic, the address will be derived automatically
# You can get testnet STX from: https://explorer.hiro.so/sandbox/faucet?chain=testnet
